/**
 * Mock seed data for local development (Менделеевская location).
 * Replaces real Supabase queries until the DB is connected (Stage 2).
 * Real photos will be sourced from barviha.ru later — placeholders for now.
 */
import type {
  Category,
  HookahMood,
  Location,
  LocationMenuItem,
  MenuCatalogItem,
  ResolvedMenuItem,
  Table,
} from './types';

export const MOCK_LOCATION: Location = {
  id: 'loc-mendeleevskaya',
  slug: 'mendeleevskaya',
  name: 'Менделеевская',
  address: 'г. Москва, ул. Образцова, 4А',
  features: ['lounge', 'karaoke', 'veranda'],
  brand_color: '#c9a961',
  created_at: '2026-01-01T00:00:00Z',
};

export const MOCK_TABLES: Table[] = Array.from({ length: 12 }, (_, i) => ({
  id: `tbl-${i + 1}`,
  location_id: MOCK_LOCATION.id,
  number: String(i + 1),
  qr_token: `mnd-t${i + 1}-${(i * 7 + 13).toString(36)}`,
}));

export const MOCK_CATEGORIES: Category[] = [
  { id: 'cat-hookah', slug: 'hookah', name: 'Кальяны', parent_id: null, sort_order: 1 },
  { id: 'cat-bar', slug: 'bar', name: 'Бар', parent_id: null, sort_order: 2 },
  { id: 'cat-kitchen', slug: 'kitchen', name: 'Кухня', parent_id: null, sort_order: 3 },
  { id: 'cat-desserts', slug: 'desserts', name: 'Десерты', parent_id: null, sort_order: 4 },
];

export const MOCK_HOOKAH_MOODS: HookahMood[] = [
  {
    id: 'mood-soft',
    slug: 'soft',
    name: 'Мягкий',
    name_en: 'Soft',
    description: 'Лёгкий, обволакивающий вкус — для долгих разговоров',
    description_en: 'Light and enveloping flavor — for long conversations',
    gradient_from: '#3a3a3a',
    gradient_to: '#1a1a1a',
    icon: '◯',
    examples: 'Молоко, груша, белый виноград, мята',
  },
  {
    id: 'mood-fresh',
    slug: 'fresh',
    name: 'Освежающий',
    name_en: 'Fresh',
    description: 'Цитрусы, мята, лёд — бодрит и тонизирует',
    description_en: 'Citrus, mint, ice — invigorating',
    gradient_from: '#2a4a3a',
    gradient_to: '#1a1a1a',
    icon: '❅',
    examples: 'Лимон, мята, лайм, грейпфрут',
  },
  {
    id: 'mood-strong',
    slug: 'strong',
    name: 'Крепкий',
    name_en: 'Strong',
    description: 'Густой дым, выраженный никотиновый удар',
    description_en: 'Thick smoke, pronounced nicotine hit',
    gradient_from: '#4a2a2a',
    gradient_to: '#1a1a1a',
    icon: '✦',
    examples: 'Tangiers, тёмный лист, без миксов',
  },
  {
    id: 'mood-fruit',
    slug: 'fruit',
    name: 'Фруктовый',
    name_en: 'Fruity',
    description: 'Сочные ноты тропических и ягодных фруктов',
    description_en: 'Juicy tropical and berry notes',
    gradient_from: '#4a3a1a',
    gradient_to: '#1a1a1a',
    icon: '✤',
    examples: 'Манго, маракуйя, малина, питахайя',
  },
  {
    id: 'mood-dessert',
    slug: 'dessert',
    name: 'Десертный',
    name_en: 'Dessert',
    description: 'Сладкие миксы — ваниль, карамель, шоколад',
    description_en: 'Sweet mixes — vanilla, caramel, chocolate',
    gradient_from: '#3a2a4a',
    gradient_to: '#1a1a1a',
    icon: '✧',
    examples: 'Ваниль, карамель, тирамису, шоколад',
  },
];

export const MOCK_CATALOG: MenuCatalogItem[] = [];
export const MOCK_LOCATION_MENU: LocationMenuItem[] = [];

export const MOCK_RESOLVED_ITEMS: ResolvedMenuItem[] = [
  {
    id: 'itm-hookah-signature',
    name: 'Барвиха Сигнатур',
    name_en: 'Barvikha Signature',
    description: 'Авторская смесь табака с нотами манго, маракуйи и мяты на молоке.',
    description_en: 'Signature tobacco blend with mango, passion fruit and mint notes on milk.',
    photo: null,
    composition: 'Премиум табак Darkside, свежая маракуйя, манго, лёд, молоко 3.2%',
    composition_en: 'Premium Darkside tobacco, fresh passion fruit, mango, ice, milk 3.2%',
    category_id: 'cat-hookah',
    price: 2800,
    weight: '60 мин',
    labels: ['hit', 'chef_pick'],
    is_available: true,
    is_premium: true,
    has_3d_model: true,
    spline_url: 'https://prod.spline.design/genkPHJBpz45HXjU/scene.splinecode',
  },
  {
    id: 'itm-hookah-black-gold',
    name: 'Чёрное золото',
    name_en: 'Black Gold',
    description: 'Чёрный виноград и инжир с лёгкой ноткой ванили.',
    description_en: 'Black grape and fig with a hint of vanilla.',
    photo: null,
    composition: 'Табак Tangiers, чёрный виноград, инжир, ваниль',
    composition_en: 'Tangiers tobacco, black grape, fig, vanilla',
    category_id: 'cat-hookah',
    price: 3200,
    weight: '60 мин',
    labels: ['premium'],
    is_available: true,
    is_premium: true,
    has_3d_model: false,
    spline_url: null,
  },
  {
    id: 'itm-hookah-classic',
    name: 'Классический',
    name_en: 'Classic',
    description: 'Двойное яблоко на классическом угле — выдержанный восточный вкус.',
    description_en: 'Double apple on classic coal — aged oriental flavor.',
    photo: null,
    composition: 'Табак Al Fakher, уголь кокосовый',
    composition_en: 'Al Fakher tobacco, coconut coal',
    category_id: 'cat-hookah',
    price: 2200,
    weight: '50 мин',
    labels: [],
    is_available: true,
    is_premium: false,
    has_3d_model: false,
    spline_url: null,
  },

  {
    id: 'itm-bar-old-fashioned',
    name: 'Олд Фэшн',
    name_en: 'Old Fashioned',
    description: 'Бурбон, сахарный сироп, биттеры, апельсиновая цедра.',
    description_en: 'Bourbon, sugar syrup, bitters, orange zest.',
    photo: null,
    composition: 'Bulleit Bourbon 50 мл, сахарный сироп, Angostura bitters, цедра апельсина',
    composition_en: 'Bulleit Bourbon 50ml, sugar syrup, Angostura bitters, orange zest',
    category_id: 'cat-bar',
    price: 990,
    weight: '120 мл',
    labels: ['hit'],
    is_available: true,
    is_premium: false,
    has_3d_model: false,
    spline_url: null,
    nutrition: { kcal: 165, protein: 0, fat: 0, carbs: 8 },
  },
  {
    id: 'itm-bar-negroni',
    name: 'Негрони',
    name_en: 'Negroni',
    description: 'Джин, Кампари, красный вермут — классический горький аперитив.',
    description_en: 'Gin, Campari, red vermouth — classic bitter aperitif.',
    photo: null,
    composition: 'Джин Tanqueray 30 мл, Campari 30 мл, Carpano Antica 30 мл, цедра апельсина',
    composition_en: 'Tanqueray gin 30ml, Campari 30ml, Carpano Antica 30ml, orange zest',
    category_id: 'cat-bar',
    price: 890,
    weight: '90 мл',
    labels: [],
    is_available: true,
    is_premium: false,
    has_3d_model: false,
    spline_url: null,
    nutrition: { kcal: 195, protein: 0, fat: 0, carbs: 7 },
  },
  {
    id: 'itm-bar-aperol',
    name: 'Апероль Шприц',
    name_en: 'Aperol Spritz',
    description: 'Просекко, Апероль, содовая — лёгкий итальянский аперитив.',
    description_en: 'Prosecco, Aperol, soda — light Italian aperitif.',
    photo: null,
    composition: 'Просекко 90 мл, Aperol 60 мл, содовая, апельсин, лёд',
    composition_en: 'Prosecco 90ml, Aperol 60ml, soda, orange, ice',
    category_id: 'cat-bar',
    price: 790,
    weight: '250 мл',
    labels: ['hit'],
    is_available: true,
    is_premium: false,
    has_3d_model: false,
    spline_url: null,
    nutrition: { kcal: 140, protein: 0, fat: 0, carbs: 11 },
  },
  {
    id: 'itm-bar-margarita',
    name: 'Маргарита',
    name_en: 'Margarita',
    description: 'Текила, трипл-сек, фреш лайма, соляной обод.',
    description_en: 'Tequila, triple sec, fresh lime, salt rim.',
    photo: null,
    composition: 'Olmeca Tequila 50 мл, Cointreau 20 мл, фреш лайма 20 мл, соль',
    composition_en: 'Olmeca Tequila 50ml, Cointreau 20ml, fresh lime 20ml, salt',
    category_id: 'cat-bar',
    price: 890,
    weight: '110 мл',
    labels: [],
    is_available: true,
    is_premium: false,
    has_3d_model: false,
    spline_url: null,
    nutrition: { kcal: 170, protein: 0, fat: 0, carbs: 5 },
  },
  {
    id: 'itm-bar-espresso-martini',
    name: 'Эспрессо Мартини',
    name_en: 'Espresso Martini',
    description: 'Водка, кофейный ликёр, свежесваренный эспрессо.',
    description_en: 'Vodka, coffee liqueur, fresh espresso.',
    photo: null,
    composition: 'Водка Beluga 40 мл, Kahlua 20 мл, эспрессо двойной, сироп ваниль',
    composition_en: 'Beluga vodka 40ml, Kahlua 20ml, double espresso, vanilla syrup',
    category_id: 'cat-bar',
    price: 990,
    weight: '120 мл',
    labels: ['chef_pick'],
    is_available: true,
    is_premium: false,
    has_3d_model: false,
    spline_url: null,
    nutrition: { kcal: 220, protein: 1, fat: 0, carbs: 12 },
  },
  {
    id: 'itm-bar-mojito',
    name: 'Мохито',
    name_en: 'Mojito',
    description: 'Белый ром, мята, лайм, тростниковый сахар, содовая.',
    description_en: 'White rum, mint, lime, cane sugar, soda.',
    photo: null,
    composition: 'Bacardi Carta Blanca 50 мл, мята свежая, лайм, тростниковый сахар, содовая',
    composition_en: 'Bacardi Carta Blanca 50ml, fresh mint, lime, cane sugar, soda',
    category_id: 'cat-bar',
    price: 690,
    weight: '300 мл',
    labels: [],
    is_available: true,
    is_premium: false,
    has_3d_model: false,
    spline_url: null,
    nutrition: { kcal: 165, protein: 0, fat: 0, carbs: 15 },
  },
  {
    id: 'itm-bar-pina-colada',
    name: 'Пина Колада',
    name_en: 'Piña Colada',
    description: 'Белый ром, кокосовый крем, ананасовый сок — тропический классик.',
    description_en: 'White rum, coconut cream, pineapple juice — tropical classic.',
    photo: null,
    composition: 'Ром Bacardi 50 мл, кокосовый крем 30 мл, ананасовый сок 90 мл, лёд',
    composition_en: 'Bacardi rum 50ml, coconut cream 30ml, pineapple juice 90ml, ice',
    category_id: 'cat-bar',
    price: 790,
    weight: '300 мл',
    labels: [],
    is_available: true,
    is_premium: false,
    has_3d_model: false,
    spline_url: null,
    nutrition: { kcal: 280, protein: 1, fat: 9, carbs: 36 },
  },
  {
    id: 'itm-bar-whiskey-sour',
    name: 'Виски Сауэр',
    name_en: 'Whiskey Sour',
    description: 'Бурбон, фреш лимона, сахарный сироп, яичный белок.',
    description_en: 'Bourbon, fresh lemon, sugar syrup, egg white.',
    photo: null,
    composition: 'Bulleit Bourbon 50 мл, фреш лимона 25 мл, сироп 15 мл, яичный белок',
    composition_en: 'Bulleit Bourbon 50ml, fresh lemon 25ml, syrup 15ml, egg white',
    category_id: 'cat-bar',
    price: 890,
    weight: '120 мл',
    labels: [],
    is_available: true,
    is_premium: false,
    has_3d_model: false,
    spline_url: null,
    nutrition: { kcal: 170, protein: 2, fat: 0, carbs: 9 },
  },
  {
    id: 'itm-bar-virgin-mojito',
    name: 'Безалкогольный мохито',
    name_en: 'Virgin Mojito',
    description: 'Мята, лайм, тростниковый сахар, содовая — освежающий и без алкоголя.',
    description_en: 'Mint, lime, cane sugar, soda — refreshing and alcohol-free.',
    photo: null,
    composition: 'Мята свежая, лайм, тростниковый сахар, содовая, лёд',
    composition_en: 'Fresh mint, lime, cane sugar, soda, ice',
    category_id: 'cat-bar',
    price: 490,
    weight: '300 мл',
    labels: [],
    is_available: true,
    is_premium: false,
    has_3d_model: false,
    spline_url: null,
    nutrition: { kcal: 85, protein: 0, fat: 0, carbs: 21 },
  },
  {
    id: 'itm-bar-lemonade-berry',
    name: 'Лимонад «Малина-Базилик»',
    name_en: 'Lemonade «Raspberry-Basil»',
    description: 'Малина, базилик, розмарин на основе игристой воды.',
    description_en: 'Raspberry, basil, rosemary on sparkling water base.',
    photo: null,
    composition: 'Малина свежая, базилик, розмарин, игристая вода, тростниковый сироп, лайм',
    composition_en: 'Fresh raspberry, basil, rosemary, sparkling water, cane syrup, lime',
    category_id: 'cat-bar',
    price: 590,
    weight: '500 мл',
    labels: ['new'],
    is_available: true,
    is_premium: false,
    has_3d_model: false,
    spline_url: null,
    nutrition: { kcal: 95, protein: 0, fat: 0, carbs: 23 },
  },
  {
    id: 'itm-bar-fresh-juice',
    name: 'Свежевыжатый сок',
    name_en: 'Fresh-squeezed juice',
    description: 'Апельсин, грейпфрут, яблоко или морковь на выбор.',
    description_en: 'Orange, grapefruit, apple or carrot — your choice.',
    photo: null,
    composition: 'Фрукты свежие',
    composition_en: 'Fresh fruits',
    category_id: 'cat-bar',
    price: 490,
    weight: '300 мл',
    labels: [],
    is_available: true,
    is_premium: false,
    has_3d_model: false,
    spline_url: null,
    nutrition: { kcal: 135, protein: 1, fat: 0, carbs: 32 },
  },
  {
    id: 'itm-bar-tea-dahongpao',
    name: 'Чай Да Хун Пао',
    name_en: 'Da Hong Pao Tea',
    description: 'Элитный улун из китайской провинции Фуцзянь.',
    description_en: 'Premium oolong from Fujian, China.',
    photo: null,
    composition: 'Чай Да Хун Пао, вода родниковая, чайник 600 мл',
    composition_en: 'Da Hong Pao tea, spring water, 600ml teapot',
    category_id: 'cat-bar',
    price: 690,
    weight: '600 мл',
    labels: [],
    is_available: true,
    is_premium: false,
    has_3d_model: false,
    spline_url: null,
    nutrition: { kcal: 1, protein: 0, fat: 0, carbs: 0 },
  },
  {
    id: 'itm-bar-tea-puer',
    name: 'Шу Пуэр',
    name_en: 'Shou Puer',
    description: 'Выдержанный землистый китайский чай с глубоким ароматом.',
    description_en: 'Aged earthy Chinese tea with a deep aroma.',
    photo: null,
    composition: 'Шу Пуэр выдержанный, вода родниковая, чайник 600 мл',
    composition_en: 'Aged Shou Puer, spring water, 600ml teapot',
    category_id: 'cat-bar',
    price: 590,
    weight: '600 мл',
    labels: [],
    is_available: true,
    is_premium: false,
    has_3d_model: false,
    spline_url: null,
    nutrition: { kcal: 1, protein: 0, fat: 0, carbs: 0 },
  },
  {
    id: 'itm-bar-cappuccino',
    name: 'Капучино',
    name_en: 'Cappuccino',
    description: 'Эспрессо двойной, взбитое молоко, лёгкая молочная пенка.',
    description_en: 'Double espresso, steamed milk, light foam.',
    photo: null,
    composition: 'Эспрессо двойной, молоко 200 мл',
    composition_en: 'Double espresso, milk 200ml',
    category_id: 'cat-bar',
    price: 390,
    weight: '250 мл',
    labels: [],
    is_available: true,
    is_premium: false,
    has_3d_model: false,
    spline_url: null,
    nutrition: { kcal: 80, protein: 4, fat: 4, carbs: 6 },
  },
  {
    id: 'itm-bar-water-sparkling',
    name: 'Перье',
    name_en: 'Perrier',
    description: 'Французская минеральная вода с натуральной газацией.',
    description_en: 'French naturally sparkling mineral water.',
    photo: null,
    composition: 'Минеральная вода Perrier 750 мл',
    composition_en: 'Perrier mineral water 750ml',
    category_id: 'cat-bar',
    price: 590,
    weight: '750 мл',
    labels: [],
    is_available: true,
    is_premium: false,
    has_3d_model: false,
    spline_url: null,
    nutrition: { kcal: 0, protein: 0, fat: 0, carbs: 0 },
  },

  {
    id: 'itm-kitchen-tartare',
    name: 'Тартар из говядины',
    name_en: 'Beef Tartare',
    description: 'Рубленая мраморная говядина, перепелиный желток, каперсы, трюфельное масло.',
    description_en: 'Chopped marbled beef, quail yolk, capers, truffle oil.',
    photo: null,
    composition: 'Говядина мраморная, перепелиное яйцо, каперсы, трюфельное масло, лук-шалот, дижонская горчица',
    composition_en: 'Marbled beef, quail egg, capers, truffle oil, shallot, Dijon mustard',
    category_id: 'cat-kitchen',
    price: 1490,
    weight: '180 г',
    labels: ['chef_pick'],
    is_available: true,
    is_premium: true,
    has_3d_model: false,
    spline_url: null,
    nutrition: { kcal: 285, protein: 22, fat: 19, carbs: 4 },
  },
  {
    id: 'itm-kitchen-caesar',
    name: 'Цезарь с креветками',
    name_en: 'Caesar with Shrimp',
    description: 'Тигровые креветки, романо, пармезан, домашний соус, чесночные крутоны.',
    description_en: 'Tiger shrimp, romaine, parmesan, house sauce, garlic croutons.',
    photo: null,
    composition: 'Креветки тигровые, салат романо, пармезан, соус Цезарь, крутоны, чеснок',
    composition_en: 'Tiger shrimp, romaine, parmesan, Caesar sauce, croutons, garlic',
    category_id: 'cat-kitchen',
    price: 1190,
    weight: '240 г',
    labels: ['hit'],
    is_available: true,
    is_premium: false,
    has_3d_model: false,
    spline_url: null,
    nutrition: { kcal: 312, protein: 24, fat: 18, carbs: 9 },
  },
  {
    id: 'itm-kitchen-ribeye',
    name: 'Стейк Рибай',
    name_en: 'Ribeye Steak',
    description: 'Премиальный стейк из мраморной говядины с гарниром из овощей гриль.',
    description_en: 'Premium marbled beef steak with grilled vegetables.',
    photo: null,
    composition: 'Говядина Black Angus, соль морская, перец чёрный, розмарин, овощи гриль, сливочное масло',
    composition_en: 'Black Angus beef, sea salt, black pepper, rosemary, grilled vegetables, butter',
    category_id: 'cat-kitchen',
    price: 3490,
    weight: '320 г',
    labels: ['premium', 'chef_pick'],
    is_available: true,
    is_premium: true,
    has_3d_model: false,
    spline_url: null,
    nutrition: { kcal: 520, protein: 42, fat: 38, carbs: 2 },
  },
  {
    id: 'itm-kitchen-tom-yum',
    name: 'Том ям с морепродуктами',
    name_en: 'Tom Yum with Seafood',
    description: 'Тайский суп на кокосовом молоке с креветками, кальмарами и мидиями.',
    description_en: 'Thai soup on coconut milk with shrimp, calamari and mussels.',
    photo: null,
    composition: 'Креветки, кальмары, мидии, кокосовое молоко, лемонграсс, лайм, перец чили',
    composition_en: 'Shrimp, calamari, mussels, coconut milk, lemongrass, lime, chili',
    category_id: 'cat-kitchen',
    price: 890,
    weight: '350 мл',
    labels: ['spicy'],
    is_available: true,
    is_premium: false,
    has_3d_model: false,
    spline_url: null,
    nutrition: { kcal: 210, protein: 16, fat: 12, carbs: 8 },
  },
  {
    id: 'itm-kitchen-burrata',
    name: 'Буррата с томатами',
    name_en: 'Burrata with Tomatoes',
    description: 'Свежая итальянская буррата с томатами черри и песто.',
    description_en: 'Fresh Italian burrata with cherry tomatoes and pesto.',
    photo: null,
    composition: 'Буррата 125 г, томаты черри, песто из базилика, кедровые орехи, бальзамик',
    composition_en: 'Burrata 125g, cherry tomatoes, basil pesto, pine nuts, balsamic',
    category_id: 'cat-kitchen',
    price: 1290,
    weight: '220 г',
    labels: ['vegan'],
    is_available: true,
    is_premium: false,
    has_3d_model: false,
    spline_url: null,
    nutrition: { kcal: 320, protein: 14, fat: 26, carbs: 8 },
  },

  {
    id: 'itm-dessert-cheesecake',
    name: 'Чизкейк Нью-Йорк',
    name_en: 'New York Cheesecake',
    description: 'Классический чизкейк с ягодным соусом и свежей мятой.',
    description_en: 'Classic cheesecake with berry sauce and fresh mint.',
    photo: null,
    composition: 'Сыр Филадельфия, песочное тесто, сливки, ягодный соус, мята',
    composition_en: 'Philadelphia cheese, shortcrust, cream, berry sauce, mint',
    category_id: 'cat-desserts',
    price: 590,
    weight: '160 г',
    labels: ['hit'],
    is_available: true,
    is_premium: false,
    has_3d_model: false,
    spline_url: null,
    nutrition: { kcal: 380, protein: 7, fat: 24, carbs: 32 },
  },
  {
    id: 'itm-dessert-tiramisu',
    name: 'Тирамису',
    name_en: 'Tiramisu',
    description: 'Классический итальянский десерт с маскарпоне и кофе амаретто.',
    description_en: 'Classic Italian dessert with mascarpone and amaretto coffee.',
    photo: null,
    composition: 'Маскарпоне, савоярди, кофе эспрессо, амаретто, какао, желтки',
    composition_en: 'Mascarpone, savoiardi, espresso, amaretto, cocoa, yolks',
    category_id: 'cat-desserts',
    price: 650,
    weight: '180 г',
    labels: ['new'],
    is_available: true,
    is_premium: false,
    has_3d_model: false,
    spline_url: null,
    nutrition: { kcal: 420, protein: 6, fat: 28, carbs: 35 },
  },
  {
    id: 'itm-dessert-honey-cake',
    name: 'Медовик',
    name_en: 'Honey Cake',
    description: 'Многослойный медовый торт со сметанным кремом.',
    description_en: 'Layered honey cake with sour cream filling.',
    photo: null,
    composition: 'Мука, мёд, яйца, сметана, сливки, грецкий орех',
    composition_en: 'Flour, honey, eggs, sour cream, cream, walnut',
    category_id: 'cat-desserts',
    price: 490,
    weight: '180 г',
    labels: [],
    is_available: true,
    is_premium: false,
    has_3d_model: false,
    spline_url: null,
    nutrition: { kcal: 405, protein: 6, fat: 22, carbs: 45 },
  },
];
