/**
 * Mock seed data for local development (Менделеевская location).
 * Real menu items, prices, compositions and KBJU sourced from Barviha's
 * spring 2026 tech card and KBJU spreadsheets.
 *
 * Photos: high-quality Unsplash images matched by content to each dish.
 * Replace with real per-dish photography when shoots are done.
 */
import type {
  Category,
  HookahMood,
  Location,
  LocationMenuItem,
  MenuCatalogItem,
  ResolvedMenuItem,
  Table,
} from './types';

const UNSPLASH = (id: string): string =>
  `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=1920&q=85`;

// Curated photo IDs — verified to return 200 on Unsplash CDN.
const PIC = {
  loungeDark: '1517248135467-4c7edcad34c4',
  loungeGold: '1572116469696-31de0f17cc34',
  loungeBottles: '1597290282695-edc43d0e7129',
  loungeBartender: '1566417713940-fe7c737a9ef2',
  whiskeyAmber: '1514362545857-3bc16c4c7d1b',
  martiniYellow: '1587223962930-cb7f31384c19',
  cocktailBerry: '1536935338788-846bb9981813',
  cocktailIced: '1556679343-c7306c1976bc',
  mojitoMint: '1551538827-9c037cb4f32a',
  brownieIcecream: '1551024506-0bccd828d307',
  teapot: '1551024601-bec78aea704b',
  caesarShrimp: '1551248429-40975aa4de74',
  greekVeggie: '1540420773420-3366772f4999',
  buddhaBowl: '1623428187969-5da2dcea5ebf',
  salmonPoke: '1546069901-ba9599a7e63c',
  cheeseBlock: '1559561853-08451507cbe7',
  steakSliced: '1452251889946-8ff5ea7b27ab',
  steakAsparagus: '1558030006-450675393462',
  chickenTomatoes: '1604908176997-125f25cc6f3d',
  burger: '1546964124-0cce460f38ef',
  tiramisu: '1567306226416-28f0efdc88ce',
  raspberryCake: '1565958011703-44f9829ba187',
  apples: '1571091718767-18b5b1457add',
} as const;

export const MOCK_LOCATIONS: Location[] = [
  {
    id: 'loc-mendeleevskaya',
    slug: 'mendeleevskaya',
    name: 'Менделеевская',
    address: 'г. Москва, ул. Образцова, 4А',
    features: ['lounge', 'karaoke', 'veranda'],
    brand_color: '#C49262',
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'loc-baumanskaya',
    slug: 'baumanskaya',
    name: 'Бауманская',
    address: 'г. Москва, ул. Бакунинская, 8',
    features: ['lounge'],
    brand_color: '#C49262',
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'loc-mitino',
    slug: 'mitino',
    name: 'Митино',
    address: 'г. Москва, Пятницкое ш., 3',
    features: ['lounge'],
    brand_color: '#C49262',
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'loc-krylatskoe',
    slug: 'krylatskoe',
    name: 'Крылатское',
    address: 'г. Москва, Рублёвское ш., 52',
    features: ['lounge', 'karaoke'],
    brand_color: '#C49262',
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'loc-rublyovka',
    slug: 'rublyovka',
    name: 'Рублёвка',
    address: 'г. Москва, Рублёво-Успенское ш., 1-й км',
    features: ['lounge', 'karaoke', 'vip_karaoke', 'veranda', 'terrace'],
    brand_color: '#C49262',
    created_at: '2026-01-01T00:00:00Z',
  },
];

// Back-compat: код, который импортит MOCK_LOCATION, продолжит работать
export const MOCK_LOCATION: Location = MOCK_LOCATIONS[0]!;

export const MOCK_TABLES: Table[] = Array.from({ length: 12 }, (_, i) => ({
  id: `tbl-${i + 1}`,
  location_id: MOCK_LOCATION.id,
  number: String(i + 1),
  qr_token: `mnd-t${i + 1}-${(i * 7 + 13).toString(36)}`,
}));

export const MOCK_CATEGORIES: Category[] = [
  { id: 'cat-hookah', slug: 'hookah', name: 'Кальяны', parent_id: null, sort_order: 1 },
  { id: 'cat-bar', slug: 'bar', name: 'Бар', parent_id: null, sort_order: 2 },
  { id: 'cat-kitchen', slug: 'kitchen', name: 'Кухня', parent_id: null, sort_order: 3 },
  { id: 'cat-rolls', slug: 'rolls', name: 'Роллы', parent_id: null, sort_order: 4 },
  { id: 'cat-desserts', slug: 'desserts', name: 'Десерты', parent_id: null, sort_order: 5 },
];

export const MOCK_HOOKAH_MOODS: HookahMood[] = [
  {
    id: 'mood-soft',
    slug: 'soft',
    name: 'Мягкий',
    name_en: 'Soft',
    description: 'Лёгкий, обволакивающий вкус — для долгих разговоров',
    description_en: 'Light and enveloping flavor — for long conversations',
    gradient_from: '#5a4a2c',
    gradient_to: '#1a1108',
    icon: '◯',
    examples: 'Молоко, груша, белый виноград, мята',
  },
  {
    id: 'mood-fresh',
    slug: 'fresh',
    name: 'Освежающий',
    name_en: 'Fresh',
    description: 'Цитрусы, мята, лёд — бодрит и тонизирует',
    description_en: 'Citrus, mint, ice — invigorating',
    gradient_from: '#1a4a44',
    gradient_to: '#081818',
    icon: '❅',
    examples: 'Лимон, мята, лайм, грейпфрут',
  },
  {
    id: 'mood-strong',
    slug: 'strong',
    name: 'Крепкий',
    name_en: 'Strong',
    description: 'Густой дым, выраженный никотиновый удар',
    description_en: 'Thick smoke, pronounced nicotine hit',
    gradient_from: '#5a1818',
    gradient_to: '#1a0606',
    icon: '✦',
    examples: 'Tangiers, тёмный лист, без миксов',
  },
  {
    id: 'mood-fruit',
    slug: 'fruit',
    name: 'Фруктовый',
    name_en: 'Fruity',
    description: 'Сочные ноты тропических и ягодных фруктов',
    description_en: 'Juicy tropical and berry notes',
    gradient_from: '#5a3814',
    gradient_to: '#1a0c04',
    icon: '✤',
    examples: 'Манго, маракуйя, малина, питахайя',
  },
  {
    id: 'mood-dessert',
    slug: 'dessert',
    name: 'Десертный',
    name_en: 'Dessert',
    description: 'Сладкие миксы — ваниль, карамель, шоколад',
    description_en: 'Sweet mixes — vanilla, caramel, chocolate',
    gradient_from: '#3a1a4a',
    gradient_to: '#0a0418',
    icon: '✧',
    examples: 'Ваниль, карамель, тирамису, шоколад',
  },
];

export const MOCK_CATALOG: MenuCatalogItem[] = [];
export const MOCK_LOCATION_MENU: LocationMenuItem[] = [];

export const MOCK_RESOLVED_ITEMS: ResolvedMenuItem[] = [
  // ============ КАЛЬЯНЫ ============
  {
    id: 'itm-hookah-barviha',
    name: 'Кальян Барвиха',
    description: 'Авторский премиум-кальян: чаша из грейпфрута/ананаса/граната, колба арбуз или тыква.',
    photo: UNSPLASH(PIC.loungeGold),
    composition: 'Чаша: грейпфрут, ананас или гранат, Колба: арбуз или тыква, Табак: любой по желанию',
    category_id: 'cat-hookah',
    price: 20000,
    weight: '90 мин',
    labels: ['premium', 'chef_pick'],
    is_available: true,
    is_premium: true,
    is_alcoholic: false,
    has_3d_model: false,
    spline_url: null,
  },
  {
    id: 'itm-hookah-tropicana-mama',
    name: 'Tropicana Mama',
    description: 'Авторский кальян на ананасе с маракуйей, киви и свежей мятой.',
    photo: UNSPLASH(PIC.mojitoMint),
    composition: 'Чаша: ананас, Сироп маракуйи, Ягоды малины, Киви, Свежая мята',
    category_id: 'cat-hookah',
    price: 7000,
    weight: '70 мин',
    labels: ['hit', 'premium'],
    is_available: true,
    is_premium: true,
    is_alcoholic: false,
    has_3d_model: false,
    spline_url: null,
  },
  {
    id: 'itm-hookah-black-edition',
    name: 'Black Edition',
    description: 'Кальян на гранате с ягодами малины, фисташками и апельсином.',
    photo: UNSPLASH(PIC.cocktailBerry),
    composition: 'Чаша: гранат, Ягоды малины, Ананасовый сок, Сироп Галлия, Фисташки, Апельсин, Свежая мята',
    category_id: 'cat-hookah',
    price: 7000,
    weight: '70 мин',
    labels: ['premium'],
    is_available: true,
    is_premium: true,
    is_alcoholic: false,
    has_3d_model: false,
    spline_url: null,
  },
  {
    id: 'itm-hookah-one-more-please',
    name: 'One More Please',
    description: 'Десертный кальян с ванильным мороженым, кокосом и малиной.',
    photo: UNSPLASH(PIC.brownieIcecream),
    composition: 'Чаша: ананас, Ванильное мороженое, Свежий кокос, Ягоды малины, Фисташки',
    category_id: 'cat-hookah',
    price: 7000,
    weight: '70 мин',
    labels: ['premium'],
    is_available: true,
    is_premium: true,
    is_alcoholic: false,
    has_3d_model: false,
    spline_url: null,
  },
  {
    id: 'itm-hookah-du-barry',
    name: 'Du Barry',
    description: 'Сладкий микс гранат-малина с клубничным мороженым и Raffaello.',
    photo: UNSPLASH(PIC.raspberryCake),
    composition: 'Чаша: гранат, Ягоды малины, Клубничное мороженое, Raffaello',
    category_id: 'cat-hookah',
    price: 7000,
    weight: '70 мин',
    labels: ['premium'],
    is_available: true,
    is_premium: true,
    is_alcoholic: false,
    has_3d_model: false,
    spline_url: null,
  },
  {
    id: 'itm-hookah-dolce-vita',
    name: 'Dolce Vita',
    description: 'Десертный кальян с кокосовым мороженым, печеньем Орео и корицей.',
    photo: UNSPLASH(PIC.tiramisu),
    composition: 'Чаша: ананас, Кокосовое мороженое, Печенье Орео, Корица, Свежая мята',
    category_id: 'cat-hookah',
    price: 7000,
    weight: '70 мин',
    labels: ['new', 'premium'],
    is_available: true,
    is_premium: true,
    is_alcoholic: false,
    has_3d_model: false,
    spline_url: null,
  },
  {
    id: 'itm-hookah-bowl-classic',
    name: 'Кальян на чаше',
    description: 'Классическая чаша, любой табак по желанию (кроме Perfume).',
    photo: UNSPLASH(PIC.loungeDark),
    composition: 'Чаша: классическая, Табак: любой по желанию, кроме Perfume',
    category_id: 'cat-hookah',
    price: 3700,
    weight: '60 мин',
    labels: [],
    is_available: true,
    is_premium: false,
    is_alcoholic: false,
    has_3d_model: false,
    spline_url: null,
  },
  {
    id: 'itm-hookah-fruit-classic',
    name: 'Кальян на фрукте',
    description: 'Чаша из грейпфрута, ананаса или граната. Любой табак.',
    photo: UNSPLASH(PIC.apples),
    composition: 'Чаша: грейпфрут, ананас или гранат, Табак: любой по желанию, кроме Perfume',
    category_id: 'cat-hookah',
    price: 4200,
    weight: '70 мин',
    labels: [],
    is_available: true,
    is_premium: false,
    is_alcoholic: false,
    has_3d_model: false,
    spline_url: null,
  },
  {
    id: 'itm-hookah-perfume-bowl',
    name: 'Perfume на чаше',
    description: 'Премиальный табак Perfume на классической чаше.',
    photo: UNSPLASH(PIC.loungeBottles),
    composition: 'Чаша: классическая, Табак: любой Perfume по желанию',
    category_id: 'cat-hookah',
    price: 5500,
    weight: '70 мин',
    labels: ['premium'],
    is_available: true,
    is_premium: true,
    is_alcoholic: false,
    has_3d_model: false,
    spline_url: null,
  },

  // ============ БАР — авторские (1100₽) ============
  {
    id: 'itm-bar-french',
    name: 'French',
    description: 'Авторский коктейль с просекко и зелёным шартрезом.',
    photo: UNSPLASH(PIC.martiniYellow),
    composition: 'Просекко, Зелёный шартрез, Цитрусовый сироп, Базилик, Лёд',
    category_id: 'cat-bar',
    price: 1100,
    weight: '180 мл',
    labels: ['chef_pick'],
    is_available: true,
    is_premium: false,
    is_alcoholic: true,
    has_3d_model: false,
    spline_url: null,
  },
  {
    id: 'itm-bar-rose-glasses',
    name: 'Rose Glasses',
    description: 'Лёгкий розовый коктейль с малиной и томатами.',
    photo: UNSPLASH(PIC.cocktailBerry),
    composition: 'Джин, Сок малины, Томаты, Сироп розы, Лёд',
    category_id: 'cat-bar',
    price: 1100,
    weight: '180 мл',
    labels: [],
    is_available: true,
    is_premium: false,
    is_alcoholic: true,
    has_3d_model: false,
    spline_url: null,
  },
  {
    id: 'itm-bar-up-your-cool',
    name: 'Up Your Cool',
    description: 'Освежающий цитрусовый коктейль на джине.',
    photo: UNSPLASH(PIC.mojitoMint),
    composition: 'Джин, Огурец, Сироп бузины, Сок лайма, Тоник, Лёд',
    category_id: 'cat-bar',
    price: 1100,
    weight: '180 мл',
    labels: ['hit'],
    is_available: true,
    is_premium: false,
    is_alcoholic: true,
    has_3d_model: false,
    spline_url: null,
  },
  {
    id: 'itm-bar-dominant',
    name: 'Dominant',
    description: 'Крепкий бурбоновый коктейль с дымным акцентом.',
    photo: UNSPLASH(PIC.whiskeyAmber),
    composition: 'Бурбон, Соус барбекю, Кленовый сироп, Биттеры, Лёд',
    category_id: 'cat-bar',
    price: 1100,
    weight: '120 мл',
    labels: [],
    is_available: true,
    is_premium: false,
    is_alcoholic: true,
    has_3d_model: false,
    spline_url: null,
  },
  {
    id: 'itm-bar-last-word',
    name: 'Last Word',
    description: 'Классика прохибишена: джин, шартрез, мараскино, лайм.',
    photo: UNSPLASH(PIC.martiniYellow),
    composition: 'Джин, Зелёный шартрез, Ликёр мараскино, Сок лайма',
    category_id: 'cat-bar',
    price: 1100,
    weight: '90 мл',
    labels: [],
    is_available: true,
    is_premium: false,
    is_alcoholic: true,
    has_3d_model: false,
    spline_url: null,
  },
  {
    id: 'itm-bar-pina-colada-author',
    name: 'Pina Colada (Author)',
    description: 'Авторская пина колада на свежем ананасе.',
    photo: UNSPLASH(PIC.cocktailIced),
    composition: 'Белый ром, Кокосовый крем, Свежий ананас, Сливки, Лёд',
    category_id: 'cat-bar',
    price: 1100,
    weight: '300 мл',
    labels: [],
    is_available: true,
    is_premium: false,
    is_alcoholic: true,
    has_3d_model: false,
    spline_url: null,
  },

  // ============ БАР — классика (950₽) ============
  {
    id: 'itm-bar-aperol-spritz',
    name: 'Aperol Spritz',
    description: 'Просекко, Aperol, содовая — классический итальянский аперитив.',
    photo: UNSPLASH(PIC.cocktailIced),
    composition: 'Просекко, Aperol, Содовая, Апельсин, Лёд',
    category_id: 'cat-bar',
    price: 950,
    weight: '250 мл',
    labels: ['hit'],
    is_available: true,
    is_premium: false,
    is_alcoholic: true,
    has_3d_model: false,
    spline_url: null,
    nutrition: { kcal: 140, protein: 0, fat: 0, carbs: 11 },
  },
  {
    id: 'itm-bar-negroni',
    name: 'Negroni',
    description: 'Джин, Кампари, красный вермут — горький классик.',
    photo: UNSPLASH(PIC.cocktailBerry),
    composition: 'Джин, Campari, Carpano Antica, Цедра апельсина, Лёд',
    category_id: 'cat-bar',
    price: 950,
    weight: '90 мл',
    labels: [],
    is_available: true,
    is_premium: false,
    is_alcoholic: true,
    has_3d_model: false,
    spline_url: null,
    nutrition: { kcal: 195, protein: 0, fat: 0, carbs: 7 },
  },
  {
    id: 'itm-bar-old-fashioned',
    name: 'Old Fashioned',
    description: 'Бурбон, сахарный сироп, биттеры, апельсиновая цедра.',
    photo: UNSPLASH(PIC.whiskeyAmber),
    composition: 'Bulleit Bourbon 50 мл, Сахарный сироп, Angostura bitters, Цедра апельсина',
    category_id: 'cat-bar',
    price: 950,
    weight: '120 мл',
    labels: [],
    is_available: true,
    is_premium: false,
    is_alcoholic: true,
    has_3d_model: false,
    spline_url: null,
    nutrition: { kcal: 165, protein: 0, fat: 0, carbs: 8 },
  },
  {
    id: 'itm-bar-margarita',
    name: 'Margarita',
    description: 'Текила, Cointreau, фреш лайма, соляной обод.',
    photo: UNSPLASH(PIC.martiniYellow),
    composition: 'Olmeca Tequila 50 мл, Cointreau 20 мл, Фреш лайма 20 мл, Соль',
    category_id: 'cat-bar',
    price: 950,
    weight: '110 мл',
    labels: [],
    is_available: true,
    is_premium: false,
    is_alcoholic: true,
    has_3d_model: false,
    spline_url: null,
    nutrition: { kcal: 170, protein: 0, fat: 0, carbs: 5 },
  },
  {
    id: 'itm-bar-gin-tonic',
    name: 'Gin & Tonic',
    description: 'Премиальный джин с тоником и цитрусовыми.',
    photo: UNSPLASH(PIC.cocktailIced),
    composition: 'Джин, Тоник, Лайм, Лёд',
    category_id: 'cat-bar',
    price: 950,
    weight: '300 мл',
    labels: [],
    is_available: true,
    is_premium: false,
    is_alcoholic: true,
    has_3d_model: false,
    spline_url: null,
    nutrition: { kcal: 175, protein: 0, fat: 0, carbs: 14 },
  },
  {
    id: 'itm-bar-mojito',
    name: 'Mojito',
    description: 'Белый ром, мята, лайм, содовая — освежающий классик.',
    photo: UNSPLASH(PIC.mojitoMint),
    composition: 'Bacardi Carta Blanca 50 мл, Мята свежая, Лайм, Тростниковый сахар, Содовая',
    category_id: 'cat-bar',
    price: 950,
    weight: '300 мл',
    labels: [],
    is_available: true,
    is_premium: false,
    is_alcoholic: true,
    has_3d_model: false,
    spline_url: null,
    nutrition: { kcal: 165, protein: 0, fat: 0, carbs: 15 },
  },
  {
    id: 'itm-bar-virgin-mojito',
    name: 'Безалкогольный мохито',
    description: 'Мята, лайм, тростниковый сахар, содовая.',
    photo: UNSPLASH(PIC.mojitoMint),
    composition: 'Мята свежая, Лайм, Тростниковый сахар, Содовая, Лёд',
    category_id: 'cat-bar',
    price: 490,
    weight: '300 мл',
    labels: [],
    is_available: true,
    is_premium: false,
    is_alcoholic: false,
    has_3d_model: false,
    spline_url: null,
    nutrition: { kcal: 85, protein: 0, fat: 0, carbs: 21 },
  },
  {
    id: 'itm-bar-lemonade-berry',
    name: 'Лимонад «Малина-Базилик»',
    description: 'Малина, базилик, розмарин на основе игристой воды.',
    photo: UNSPLASH(PIC.cocktailBerry),
    composition: 'Малина свежая, Базилик, Розмарин, Игристая вода, Тростниковый сироп, Лайм',
    category_id: 'cat-bar',
    price: 590,
    weight: '500 мл',
    labels: ['new'],
    is_available: true,
    is_premium: false,
    is_alcoholic: false,
    has_3d_model: false,
    spline_url: null,
    nutrition: { kcal: 95, protein: 0, fat: 0, carbs: 23 },
  },
  {
    id: 'itm-bar-tea-dahongpao',
    name: 'Чай Да Хун Пао',
    description: 'Элитный улун из китайской провинции Фуцзянь.',
    photo: UNSPLASH(PIC.teapot),
    composition: 'Чай Да Хун Пао, Вода родниковая, Чайник 600 мл',
    category_id: 'cat-bar',
    price: 690,
    weight: '600 мл',
    labels: [],
    is_available: true,
    is_premium: false,
    is_alcoholic: false,
    has_3d_model: false,
    spline_url: null,
    nutrition: { kcal: 1, protein: 0, fat: 0, carbs: 0 },
  },

  // ============ КУХНЯ ============
  {
    id: 'itm-kitchen-caesar-shrimp',
    name: 'Классический Цезарь с креветками',
    description: 'Романо, креветки гриль, томаты черри, пармезан, соус Цезарь, сухарики.',
    photo: UNSPLASH(PIC.caesarShrimp),
    composition: 'Романо, Креветки гриль, Томаты черри, Сыр пармезан, Соус цезарь, Сухарики',
    category_id: 'cat-kitchen',
    price: 890,
    weight: '260 г',
    labels: ['hit'],
    is_available: true,
    is_premium: false,
    is_alcoholic: false,
    has_3d_model: false,
    spline_url: null,
    nutrition: { kcal: 694, protein: 35, fat: 49, carbs: 19 },
  },
  {
    id: 'itm-kitchen-greek-salad',
    name: 'Салат Греческий',
    description: 'Огурцы, томаты, лук красный, каперсы, брынза, болгарский перец, маслины.',
    photo: UNSPLASH(PIC.greekVeggie),
    composition: 'Огурцы, Томаты, Лук красный, Каперсы, Брынза, Болгарский перец, Маслины каламата, Крем-чиз, Масло оливковое',
    category_id: 'cat-kitchen',
    price: 750,
    weight: '300 г',
    labels: ['vegan'],
    is_available: true,
    is_premium: false,
    is_alcoholic: false,
    has_3d_model: false,
    spline_url: null,
    nutrition: { kcal: 354, protein: 9, fat: 28, carbs: 18 },
  },
  {
    id: 'itm-kitchen-tartare-beef',
    name: 'Тартар из говядины классический',
    description: 'Отруб говяжий, перепелиное яйцо, каперсы, лук шалот, бородинский хлеб.',
    photo: UNSPLASH(PIC.steakSliced),
    composition: 'Отруб говяжий, Огурцы маринованные, Каперсы, Лук шалот, Яйцо перепелиное, Горчица столовая, Горчица зернистая, Бородинский хлеб, Чёрная соль, Масло оливковое',
    category_id: 'cat-kitchen',
    price: 990,
    weight: '160 г',
    labels: ['chef_pick'],
    is_available: true,
    is_premium: true,
    is_alcoholic: false,
    has_3d_model: false,
    spline_url: null,
    nutrition: { kcal: 285, protein: 22, fat: 19, carbs: 4 },
  },
  {
    id: 'itm-kitchen-tartare-salmon',
    name: 'Тартар из лосося',
    description: 'Лосось, авокадо, лук шалот, соус юдзу, трюфельное масло.',
    photo: UNSPLASH(PIC.salmonPoke),
    composition: 'Лосось филе, Авокадо, Лук шалот, Соус юдзу, Соевый соус, Масло трюфельное, Уксус мирин, Апельсин, Чёрный перец',
    category_id: 'cat-kitchen',
    price: 1090,
    weight: '152 г',
    labels: ['chef_pick'],
    is_available: true,
    is_premium: true,
    is_alcoholic: false,
    has_3d_model: false,
    spline_url: null,
    nutrition: { kcal: 312, protein: 24, fat: 21, carbs: 5 },
  },
  {
    id: 'itm-kitchen-bruschetta-salmon',
    name: 'Брускетта с лососем',
    description: 'Хлеб санчос, лосось с/с, апельсин, креметте, икра масаго, юдзу.',
    photo: UNSPLASH(PIC.salmonPoke),
    composition: 'Хлеб санчос, Лосось слабосолёный, Апельсин, Сыр креметте, Огурцы, Укроп, Икра масаго чёрная, Масло оливковое, Соус юдзу',
    category_id: 'cat-kitchen',
    price: 590,
    weight: '183 г',
    labels: [],
    is_available: true,
    is_premium: false,
    is_alcoholic: false,
    has_3d_model: false,
    spline_url: null,
    nutrition: { kcal: 407, protein: 18, fat: 22, carbs: 33 },
  },
  {
    id: 'itm-kitchen-bruschetta-roastbeef',
    name: 'Брускетта с ростбифом',
    description: 'Хлеб санчос, ростбиф, печёный кабачок и баклажан, ореховый соус.',
    photo: UNSPLASH(PIC.steakSliced),
    composition: 'Хлеб санчос, Ростбиф из говяжьей вырезки, Кабачок печёный, Баклажан печёный, Перец болгарский печёный, Огурец, Соус ореховый, Кинза',
    category_id: 'cat-kitchen',
    price: 690,
    weight: '181 г',
    labels: [],
    is_available: true,
    is_premium: false,
    is_alcoholic: false,
    has_3d_model: false,
    spline_url: null,
    nutrition: { kcal: 431, protein: 18, fat: 25, carbs: 33 },
  },
  {
    id: 'itm-kitchen-cheese-plate',
    name: 'Сырная тарелка',
    description: 'Бри, пармезан, монтазио с трюфелем, джерси блю, мёд, орех, виноград.',
    photo: UNSPLASH(PIC.cheeseBlock),
    composition: 'Бри, Пармезан, Монтазио с трюфелем, Джерси блю с голубой плесенью, Мёд, Мята, Грецкий орех, Клубника, Виноград, Гриссини',
    category_id: 'cat-kitchen',
    price: 1690,
    weight: '326 г',
    labels: ['premium'],
    is_available: true,
    is_premium: true,
    is_alcoholic: false,
    has_3d_model: false,
    spline_url: null,
    nutrition: { kcal: 1102, protein: 56, fat: 79, carbs: 39 },
  },
  {
    id: 'itm-kitchen-meat-plate',
    name: 'Мясная тарелка',
    description: 'Брезаола, копчёная утиная грудка, ростбиф, оливки, томаты вяленые.',
    photo: UNSPLASH(PIC.steakAsparagus),
    composition: 'Брезаола вяленое мясо, Грудка утиная копчёная, Ростбиф, Оливки гигантские, Томаты вяленые, Гриссини',
    category_id: 'cat-kitchen',
    price: 1100,
    weight: '180 г',
    labels: [],
    is_available: true,
    is_premium: false,
    is_alcoholic: false,
    has_3d_model: false,
    spline_url: null,
    nutrition: { kcal: 414, protein: 37, fat: 26, carbs: 8 },
  },
  {
    id: 'itm-kitchen-veggie-set',
    name: 'Овощной сет',
    description: 'Болгарский перец, огурцы, черри, сельдерей, морковь, руккола + соус блючиз.',
    photo: UNSPLASH(PIC.buddhaBowl),
    composition: 'Перец болгарский, Огурцы, Томаты черри, Стебель сельдерея, Морковь, Руккола, Соус блючиз',
    category_id: 'cat-kitchen',
    price: 690,
    weight: '755 г',
    labels: ['vegan'],
    is_available: true,
    is_premium: false,
    is_alcoholic: false,
    has_3d_model: false,
    spline_url: null,
    nutrition: { kcal: 533, protein: 13, fat: 41, carbs: 26 },
  },
  {
    id: 'itm-kitchen-tom-yum',
    name: 'Том ям с морепродуктами',
    description: 'Тайский суп на кокосовом молоке с креветками, кальмарами и мидиями.',
    photo: UNSPLASH(PIC.chickenTomatoes),
    composition: 'Креветки, Кальмары, Мидии, Кокосовое молоко, Лемонграсс, Лайм, Перец чили, Грибы шиитаке',
    category_id: 'cat-kitchen',
    price: 990,
    weight: '386 г',
    labels: ['spicy'],
    is_available: true,
    is_premium: false,
    is_alcoholic: false,
    has_3d_model: false,
    spline_url: null,
    nutrition: { kcal: 354, protein: 22, fat: 18, carbs: 26 },
  },
  {
    id: 'itm-kitchen-ribeye',
    name: 'Стейк Рибай PRIME BEEF',
    description: 'Премиальный мраморный стейк с зелёным сливочным маслом.',
    photo: UNSPLASH(PIC.steakAsparagus),
    composition: 'Говядина Black Angus, Зелёное сливочное масло, Соль морская, Перец чёрный, Розмарин',
    category_id: 'cat-kitchen',
    price: 2300,
    weight: '100 г',
    labels: ['premium', 'chef_pick'],
    is_available: true,
    is_premium: true,
    is_alcoholic: false,
    has_3d_model: false,
    spline_url: null,
    nutrition: { kcal: 253, protein: 21, fat: 18, carbs: 0 },
  },
  {
    id: 'itm-kitchen-burger-barviha',
    name: 'Бургер Барвиха',
    description: 'Двойная котлета из мраморной говядины, бекон, сыр, ягодный соус.',
    photo: UNSPLASH(PIC.burger),
    composition: 'Котлета из мраморной говядины (двойная), Бекон, Сыр чеддер, Ягодный соус, Помидор, Салат, Булочка бриошь',
    category_id: 'cat-kitchen',
    price: 1290,
    weight: '515 г',
    labels: ['hit'],
    is_available: true,
    is_premium: false,
    is_alcoholic: false,
    has_3d_model: false,
    spline_url: null,
    nutrition: { kcal: 1326, protein: 56, fat: 88, carbs: 72 },
  },

  // ============ ДЕСЕРТЫ ============
  {
    id: 'itm-dessert-cheesecake',
    name: 'Чизкейк',
    description: 'Классический чизкейк на песочной основе с ягодным соусом.',
    photo: UNSPLASH(PIC.raspberryCake),
    composition: 'Сыр Филадельфия, Песочное тесто, Сливки, Ягодный соус, Мята',
    category_id: 'cat-desserts',
    price: 590,
    weight: '187 г',
    labels: ['hit'],
    is_available: true,
    is_premium: false,
    is_alcoholic: false,
    has_3d_model: false,
    spline_url: null,
    nutrition: { kcal: 609, protein: 10, fat: 42, carbs: 49 },
  },
  {
    id: 'itm-dessert-tiramisu',
    name: 'Тирамису',
    description: 'Итальянская классика — маскарпоне, савоярди, эспрессо, амаретто.',
    photo: UNSPLASH(PIC.tiramisu),
    composition: 'Маскарпоне, Савоярди, Кофе эспрессо, Амаретто, Какао, Желтки',
    category_id: 'cat-desserts',
    price: 650,
    weight: '153 г',
    labels: ['new'],
    is_available: true,
    is_premium: false,
    is_alcoholic: false,
    has_3d_model: false,
    spline_url: null,
    nutrition: { kcal: 538, protein: 9, fat: 38, carbs: 41 },
  },
  {
    id: 'itm-dessert-honey-cake',
    name: 'Медовик',
    description: 'Многослойный медовый торт со сметанным кремом и грецким орехом.',
    photo: UNSPLASH(PIC.brownieIcecream),
    composition: 'Мука, Мёд, Яйца, Сметана, Сливки, Грецкий орех',
    category_id: 'cat-desserts',
    price: 490,
    weight: '287 г',
    labels: [],
    is_available: true,
    is_premium: false,
    is_alcoholic: false,
    has_3d_model: false,
    spline_url: null,
    nutrition: { kcal: 707, protein: 12, fat: 38, carbs: 80 },
  },
];

// ============================================================================
// РОЛЛЫ — отдельная категория, эксклюзив для Рублёвки (там нет классической кухни)
// ============================================================================
const ROLL_PIC = (id: string): string =>
  `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=1920&q=85`;

export const MOCK_ROLLS: ResolvedMenuItem[] = [
  {
    id: 'itm-roll-philadelphia',
    name: 'Филадельфия классик',
    description: 'Лосось, сливочный сыр Филадельфия, свежий огурец, нори.',
    photo: ROLL_PIC('1579871494447-9811cf80d66c'),
    composition: 'Лосось, сыр Филадельфия, огурец, рис, нори',
    category_id: 'cat-rolls',
    price: 750,
    weight: '230 г',
    labels: ['hit'],
    is_available: true,
    is_premium: false,
    is_alcoholic: false,
    has_3d_model: false,
    spline_url: null,
    nutrition: { kcal: 380, protein: 14, fat: 18, carbs: 38 },
  },
  {
    id: 'itm-roll-california',
    name: 'Калифорния с крабом',
    description: 'Краб, авокадо, огурец, обсыпан икрой тобико.',
    photo: ROLL_PIC('1607301406259-dfb186e15de8'),
    composition: 'Краб, авокадо, огурец, икра тобико, рис, нори',
    category_id: 'cat-rolls',
    price: 690,
    weight: '210 г',
    labels: [],
    is_available: true,
    is_premium: false,
    is_alcoholic: false,
    has_3d_model: false,
    spline_url: null,
    nutrition: { kcal: 320, protein: 11, fat: 12, carbs: 42 },
  },
  {
    id: 'itm-roll-unagi-maki',
    name: 'Унаги маки',
    description: 'Угорь горячего копчения, огурец, унаги-соус, кунжут.',
    photo: ROLL_PIC('1617196034796-73dfa7b1fd56'),
    composition: 'Угорь, огурец, соус унаги, кунжут, рис, нори',
    category_id: 'cat-rolls',
    price: 850,
    weight: '215 г',
    labels: ['chef_pick'],
    is_available: true,
    is_premium: false,
    is_alcoholic: false,
    has_3d_model: false,
    spline_url: null,
    nutrition: { kcal: 410, protein: 16, fat: 14, carbs: 48 },
  },
  {
    id: 'itm-roll-spicy-tuna',
    name: 'Спайси тунец',
    description: 'Свежий тунец, спайси-соус, перец чили, кинза.',
    photo: ROLL_PIC('1611141647617-6cdbf7d4ee62'),
    composition: 'Тунец, спайси-соус, чили, кинза, рис, нори',
    category_id: 'cat-rolls',
    price: 720,
    weight: '220 г',
    labels: ['spicy'],
    is_available: true,
    is_premium: false,
    is_alcoholic: false,
    has_3d_model: false,
    spline_url: null,
    nutrition: { kcal: 360, protein: 19, fat: 9, carbs: 44 },
  },
  {
    id: 'itm-roll-salmon-tempura',
    name: 'Лосось темпура',
    description: 'Лосось в хрустящей темпуре, спайси-майо, обжарка.',
    photo: ROLL_PIC('1546069901-ba9599a7e63c'),
    composition: 'Лосось, темпура, спайси-майо, рис, нори',
    category_id: 'cat-rolls',
    price: 790,
    weight: '240 г',
    labels: ['hit'],
    is_available: true,
    is_premium: false,
    is_alcoholic: false,
    has_3d_model: false,
    spline_url: null,
    nutrition: { kcal: 480, protein: 17, fat: 22, carbs: 54 },
  },
  {
    id: 'itm-roll-baked-salmon',
    name: 'Запечённый с лососем',
    description: 'Под сырной шапкой, запечён в духовке до золотистой корки.',
    photo: ROLL_PIC('1559847844-5315695dadae'),
    composition: 'Лосось, сыр, спайси-соус, рис, нори',
    category_id: 'cat-rolls',
    price: 690,
    weight: '230 г',
    labels: [],
    is_available: true,
    is_premium: false,
    is_alcoholic: false,
    has_3d_model: false,
    spline_url: null,
    nutrition: { kcal: 420, protein: 18, fat: 19, carbs: 42 },
  },
  {
    id: 'itm-roll-rainbow',
    name: 'Рейнбоу',
    description: 'Микс рыбы сверху: лосось, тунец, угорь, авокадо.',
    photo: ROLL_PIC('1583623025817-d180a2221d0a'),
    composition: 'Лосось, тунец, угорь, авокадо, рис, нори',
    category_id: 'cat-rolls',
    price: 850,
    weight: '250 г',
    labels: ['chef_pick'],
    is_available: true,
    is_premium: false,
    is_alcoholic: false,
    has_3d_model: false,
    spline_url: null,
    nutrition: { kcal: 440, protein: 22, fat: 16, carbs: 48 },
  },
  {
    id: 'itm-roll-sake-maki',
    name: 'Сяке маки',
    description: 'Классический маленький ролл с лососем.',
    photo: ROLL_PIC('1563612116-1b1e4be8b5a0'),
    composition: 'Лосось, рис, нори',
    category_id: 'cat-rolls',
    price: 450,
    weight: '160 г',
    labels: [],
    is_available: true,
    is_premium: false,
    is_alcoholic: false,
    has_3d_model: false,
    spline_url: null,
    nutrition: { kcal: 240, protein: 11, fat: 5, carbs: 38 },
  },
  {
    id: 'itm-roll-set-barvikha',
    name: 'Сет «Барвиха»',
    description: 'Авторский микс — 48 шт. Идеально для компании 3–4 человек.',
    photo: ROLL_PIC('1617196034796-73dfa7b1fd56'),
    composition: 'Филадельфия + Калифорния + Унаги-маки + Спайси тунец, 48 шт',
    category_id: 'cat-rolls',
    price: 2200,
    weight: '950 г',
    labels: ['hit', 'chef_pick'],
    is_available: true,
    is_premium: false,
    is_alcoholic: false,
    has_3d_model: false,
    spline_url: null,
  },
  {
    id: 'itm-roll-set-premium',
    name: 'Сет «Премиум»',
    description: 'С угрем, тунцом и икрой. Лучшие позиции в одном сете.',
    photo: ROLL_PIC('1607301406259-dfb186e15de8'),
    composition: 'Унаги + Рейнбоу + Лосось темпура + Запечённый, с икрой и угрём, 56 шт',
    category_id: 'cat-rolls',
    price: 3500,
    weight: '1100 г',
    labels: ['premium', 'chef_pick'],
    is_available: true,
    is_premium: true,
    is_alcoholic: false,
    has_3d_model: false,
    spline_url: null,
  },
];

// ============================================================================
// ПРАВИЛА ЦЕН ПО ЛОКАЦИЯМ
// ============================================================================
export const LOCATION_PRICING: Record<string, { discount?: number; allowedCategories?: string[] }> = {
  // Бюджетные точки — всё меню на 25% дешевле, округление до 50 ₽
  'baumanskaya':  { discount: 0.25 },
  'mitino':       { discount: 0.25 },
  'krylatskoe':   { discount: 0.25 },
  // Рублёвка — премиум, без скидки, но в категории «Кухня» вместо обычной — только роллы
  // (бар, кальяны, десерты — стандартные)
  'rublyovka':    { allowedCategories: ['cat-hookah', 'cat-bar', 'cat-rolls', 'cat-desserts'] },
};

function roundTo50(n: number): number {
  return Math.round(n / 50) * 50;
}

// ВСЕ блюда сети (основа + роллы)
export const MOCK_ALL_ITEMS: ResolvedMenuItem[] = [...MOCK_RESOLVED_ITEMS, ...MOCK_ROLLS];

// Резолвер: возвращает меню с учётом скидки и whitelist категорий
export function resolveMenuForLocation(slug: string): ResolvedMenuItem[] {
  const cfg = LOCATION_PRICING[slug] || {};
  let items = MOCK_ALL_ITEMS;
  // На обычных точках роллы скрыты — они только для Рублёвки (если потом захотим
  // открыть и для других — уберём фильтр или добавим в allowedCategories).
  if (!cfg.allowedCategories) {
    items = items.filter((it) => it.category_id !== 'cat-rolls');
  } else {
    items = items.filter((it) => cfg.allowedCategories!.includes(it.category_id || ''));
  }
  if (cfg.discount) {
    items = items.map((it) => ({ ...it, price: roundTo50(it.price * (1 - cfg.discount!)) }));
  }
  return items;
}
